/*
 * ProfileReaderFrame.java
 *
 * Created on June 10, 2008, 3:27 PM
 */

package icc_profilereader;

import java.io.File;
import javax.swing.JFileChooser;

import javax.swing.JTable;

/**
 *
 * @author  Vicky
 */
public class ProfileReaderFrame extends javax.swing.JFrame {
//ICCProfile icc=new ICCProfile("C:\\WINDOWS\\system32\\spool\\drivers\\color\\AdobeRGB1998.icc");
    /** Creates new form ProfileReaderFrame */
    String[] details;
    
    public ProfileReaderFrame() {
        initComponents();
        txtProfileDesc.setText("Tag Number\tSignature\tOffset\tSize");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowse = new javax.swing.JButton();
        txtPathName = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lblSize = new javax.swing.JLabel();
        lblCMMType = new javax.swing.JLabel();
        lblVersionNumber = new javax.swing.JLabel();
        lblDeviceClass = new javax.swing.JLabel();
        lblPCS = new javax.swing.JLabel();
        lblColorSpace = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblProfileSignature = new javax.swing.JLabel();
        lblFlags = new javax.swing.JLabel();
        lblManufacturer = new javax.swing.JLabel();
        lblPlatform = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        lblAttribute = new javax.swing.JLabel();
        lblIntent = new javax.swing.JLabel();
        lblIlluminant = new javax.swing.JLabel();
        lblProfileID = new javax.swing.JLabel();
        lblCreator = new javax.swing.JLabel();
        lblCMMType1 = new javax.swing.JLabel();
        lblSize1 = new javax.swing.JLabel();
        lblVersionNumber1 = new javax.swing.JLabel();
        lblDeviceClass1 = new javax.swing.JLabel();
        lblPCS1 = new javax.swing.JLabel();
        lblColorSpace1 = new javax.swing.JLabel();
        lblDate1 = new javax.swing.JLabel();
        lblProfileSignature1 = new javax.swing.JLabel();
        lblFlags1 = new javax.swing.JLabel();
        lblManufacturer1 = new javax.swing.JLabel();
        lblPlatform1 = new javax.swing.JLabel();
        lblModel1 = new javax.swing.JLabel();
        lblAttribute1 = new javax.swing.JLabel();
        lblIntent1 = new javax.swing.JLabel();
        lblIlluminant1 = new javax.swing.JLabel();
        lblProfileID1 = new javax.swing.JLabel();
        lblCreator1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProfileDesc = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ICC Profile Viewer");

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblSize.setText("Size : ");

        lblCMMType.setText("CMM Type : ");

        lblVersionNumber.setText("Version Number : ");

        lblDeviceClass.setText("Device Class : ");

        lblPCS.setText("PCS : ");

        lblColorSpace.setText("Color Space : ");

        lblDate.setText("Date : ");

        lblProfileSignature.setText("Profile Signature : ");

        lblFlags.setText("Flags : ");

        lblManufacturer.setText("Manufacturer : ");

        lblPlatform.setText("Platform : ");

        lblModel.setText("Model : ");

        lblAttribute.setText("Attribute : ");

        lblIntent.setText("Intent : ");

        lblIlluminant.setText("Illuminant : ");

        lblProfileID.setText("Profile ID : ");

        lblCreator.setText("Creator : ");

        lblCMMType1.setText(" ");

        lblSize1.setText(" ");

        lblVersionNumber1.setText(" ");

        lblDeviceClass1.setText(" ");

        lblPCS1.setText(" ");

        lblColorSpace1.setText(" ");

        lblDate1.setText(" ");

        lblProfileSignature1.setText(" ");

        lblFlags1.setText(" ");

        lblManufacturer1.setText(" ");

        lblPlatform1.setText(" ");

        lblModel1.setText(" ");

        lblAttribute1.setText(" ");

        lblIntent1.setText(" ");

        lblIlluminant1.setText(" ");

        lblProfileID1.setText(" ");

        lblCreator1.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSize, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCMMType, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVersionNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeviceClass, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPCS, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblColorSpace, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfileSignature, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFlags, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblManufacturer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPlatform, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblModel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblAttribute, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIntent, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIlluminant, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblProfileID, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCreator, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblCMMType1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSize1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVersionNumber1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDeviceClass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPCS1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblColorSpace1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProfileSignature1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFlags1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblManufacturer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPlatform1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblModel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAttribute1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIntent1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblIlluminant1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProfileID1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCreator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSize)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCMMType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVersionNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeviceClass)
                        .addGap(1, 1, 1)
                        .addComponent(lblColorSpace)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPCS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfileSignature)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatform)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFlags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblManufacturer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModel)
                        .addGap(9, 9, 9)
                        .addComponent(lblAttribute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIlluminant)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreator)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfileID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblSize1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCMMType1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblVersionNumber1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDeviceClass1)
                        .addGap(1, 1, 1)
                        .addComponent(lblColorSpace1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPCS1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDate1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfileSignature1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlatform1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFlags1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblManufacturer1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblModel1)
                        .addGap(9, 9, 9)
                        .addComponent(lblAttribute1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIntent1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblIlluminant1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCreator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblProfileID1))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblAttribute, lblCMMType, lblColorSpace, lblCreator, lblDate, lblDeviceClass, lblFlags, lblIlluminant, lblIntent, lblManufacturer, lblModel, lblPCS, lblPlatform, lblProfileID, lblProfileSignature, lblSize, lblVersionNumber});

        txtProfileDesc.setColumns(20);
        txtProfileDesc.setRows(5);
        jScrollPane1.setViewportView(txtProfileDesc);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPathName, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBrowse)
                    .addComponent(txtPathName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        JFileChooser jfc=new JFileChooser("C:\\WINDOWS\\system32\\spool\\drivers\\color\\AdobeRGB1998.icc\\");
        File file=null;
       jfc.showOpenDialog(this);
        file=jfc.getSelectedFile();
        if(jfc.getSelectedFile()!=null) {
        txtPathName.setText(file.getAbsolutePath() +"\\" +file.getName());
        if(file!=null) {
            ICCProfile icc=new ICCProfile(file);
            lblSize1.setText(String.valueOf(icc.profileSize));
            lblCMMType1.setText(icc.CMMType);
            lblColorSpace1.setText(icc.colorSpace);
            lblCreator1.setText(icc.profileCreator);
            lblDate1.setText(icc.strDate);
            lblDeviceClass1.setText(icc.className);
            lblFlags1.setText(icc.flagDesc);
            lblIlluminant1.setText(icc.illuminant.strXYZ);
            lblIntent1.setText(icc.renderingIntent);
            lblManufacturer1.setText(icc.deviceMfg);
            lblModel1.setText(icc.deviceModel);
            lblPCS1.setText(icc.PCS);
            lblPlatform1.setText(icc.platform);
            lblProfileID1.setText("Space for future expansion");
            lblProfileSignature1.setText(String.valueOf(icc.profileSignature));
            lblAttribute1.setText(icc.attributes);
            lblVersionNumber1.setText(String.valueOf(icc.profileVersionNumber));
            details=new String[icc.numberOfTags];

            for(int i=0;i<icc.numberOfTags;i++) {
                txtProfileDesc.setText(txtProfileDesc.getText() + "\n" +icc.xprofile.tag[i].getProfileString());
            }

        }
        }       //end of if

    }//GEN-LAST:event_btnBrowseActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileReaderFrame().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify

    // End of variables declaration
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAttribute;
    private javax.swing.JLabel lblAttribute1;
    private javax.swing.JLabel lblCMMType;
    private javax.swing.JLabel lblCMMType1;
    private javax.swing.JLabel lblColorSpace;
    private javax.swing.JLabel lblColorSpace1;
    private javax.swing.JLabel lblCreator;
    private javax.swing.JLabel lblCreator1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDate1;
    private javax.swing.JLabel lblDeviceClass;
    private javax.swing.JLabel lblDeviceClass1;
    private javax.swing.JLabel lblFlags;
    private javax.swing.JLabel lblFlags1;
    private javax.swing.JLabel lblIlluminant;
    private javax.swing.JLabel lblIlluminant1;
    private javax.swing.JLabel lblIntent;
    private javax.swing.JLabel lblIntent1;
    private javax.swing.JLabel lblManufacturer;
    private javax.swing.JLabel lblManufacturer1;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblModel1;
    private javax.swing.JLabel lblPCS;
    private javax.swing.JLabel lblPCS1;
    private javax.swing.JLabel lblPlatform;
    private javax.swing.JLabel lblPlatform1;
    private javax.swing.JLabel lblProfileID;
    private javax.swing.JLabel lblProfileID1;
    private javax.swing.JLabel lblProfileSignature;
    private javax.swing.JLabel lblProfileSignature1;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSize1;
    private javax.swing.JLabel lblVersionNumber;
    private javax.swing.JLabel lblVersionNumber1;
    private javax.swing.JTextField txtPathName;
    private javax.swing.JTextArea txtProfileDesc;
    // End of variables declaration//GEN-END:variables
    
}
